apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcover-deployment
  labels:
    app: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: app
        image: 847370586410.dkr.ecr.eu-west-1.amazonaws.com/my-cool-application:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000